### ISSUE TITLE
[ocaml.org] Update OCamllabs page

### ISSUE THREAD

**Issue by dbuenzli** [ocamllabs/Projects#16]
The funding status by Jane Street here http://ocaml.org/ocamllabs/ is outdated.

**Comment by avsm** [comment]
I didn't realise there was an OCaml Labs subpage at all -- it would be good to not replicate this information and to ensure it links back to whichever page referred to it in the first place.

**Comment by dbuenzli** [comment]
It is linked from the http://ocaml.org/community/support.html page.
