### ISSUE TITLE
[ICFP]: Canopy for liveblogging

### ISSUE THREAD

**Issue by GemmaG** [ocamllabs/Projects#5]
Generate a new Canopy for ICFP liveblogging/reporting purposes.

Need to know which features are needed for this...

- [ ] multiple tags e.g. "icfp", "icfp liveblog", "icfp article"
- [ ] @engil: check through existing canopy issues to see which are still relevant: https://github.com/Engil/Canopy/issues

@engil: please add features you think are needed, and which you think can be done in time.

**Comment by GemmaG** [comment]
We need to have Canopy ready to serve our liveblogging info - can we determine what we need for this and how far away we are from it?

**Comment by Engil** [comment]
I've been terribly unavailable the last two weeks and I'm sorry about that.
This can be done by tomorrow evening when I should be available.
We only need search by multiple tags, and filter atom feeds by tags, right ?
